# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcse15xkwffrwKqV10UhSv1Xp29AtR7s
"""


# Cellule à ajouter dans ton notebook AVANT de lancer app.py
import os
os.makedirs("/content/.streamlit", exist_ok=True)

with open("/content/.streamlit/secrets.toml", "w") as f:
    f.write("""
GROQ_API_KEY = "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"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6ZmZkZWEyZGUtNTcwYS00ODdkLWE5MWYtNTIxYTdiOWU4ZmExIn0.9NypHf_ieEupVaLD4gqRUK5O7v7wvdEGsFMUz8O9noA"
QDRANT_URL = "https://5b834079-6f0a-47f4-845e-8eed9fac8f51.europe-west3-0.gcp.cloud.qdrant.io"
""")

import streamlit as st
from qdrant_client import QdrantClient
from sentence_transformers import SentenceTransformer
from groq import Groq

# Charger les secrets depuis st.secrets (pas des variables en dur !)
GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
QDRANT_API_KEY = st.secrets["QDRANT_API_KEY"]
QDRANT_URL = st.secrets["QDRANT_URL"]

COLLECTION_NAME = "gots_standard"
VECTOR_SIZE = 1024
LLM_MODEL = "llama-3.3-70b-versatile"

@st.cache_resource
def load_clients():
    model = SentenceTransformer("BAAI/bge-m3")
    qdrant = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
    groq_client = Groq(api_key=GROQ_API_KEY)
    return model, qdrant, groq_client

model, qdrant_client, groq_client = load_clients()

st.title("RAG GOTS v7.0 — Llama 3.3 70B + Qdrant")

question = st.text_input("Votre question sur la norme GOTS :")

if question:
    with st.spinner("Recherche en cours..."):
        query_vector = model.encode(question, normalize_embeddings=True).tolist()
        results = qdrant_client.query_points(
            collection_name=COLLECTION_NAME,
            query=query_vector,
            limit=5,
            with_payload=True
        )
        context = "\n\n---\n\n".join(
            [f"[Page {r.payload['page']}]\n{r.payload['text']}" for r in results.points]
        )
        response = groq_client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": "Tu es un expert GOTS. Réponds en français depuis le contexte."},
                {"role": "user", "content": f"Contexte:\n{context}\n\nQuestion: {question}"}
            ],
            temperature=0.2,
            max_tokens=1024
        )
        st.markdown(response.choices[0].message.content)
        with st.expander("Sources"):
            for r in results.points:
                st.write(f"Page {r.payload['page']} — score: {r.score:.3f}")
